interview_config:
  total_blocks: 10
  questions_per_block: 5
  max_followup_questions: 3

blocks:
  - id: 1
    name: "childhood_family"
    title: "Детство и семья"
    context_prompt: |
      Задавай теплые, располагающие вопросы о семье, детских воспоминаниях, формирующих событиях.
      Будь внимателен к эмоциональным реакциям и готов углубиться в важные темы.
      Используй техники глубинного интервью для понимания семейной динамики и её влияния на личность.
    focus_areas:
      - "Структура семьи и семейные роли"
      - "Ключевые детские воспоминания и события"
      - "Влияние родителей на формирование характера"
      - "Ранние проявления личности и интересов"
      - "Отношения с братьями и сестрами"
    
  - id: 2
    name: "education_growth"
    title: "Образование и личностный рост"
    context_prompt: |
      Основываясь на семейном фоне, изучай образовательный путь и формирование личности.
      Учитывай влияние семьи на выбор образования и развитие интересов.
      Ищи связи между детством и образовательными решениями, выявляй ключевые моменты роста.
    focus_areas:
      - "Образовательные выборы и их мотивация"
      - "Стиль обучения и предпочтения"
      - "Влияние учителей и наставников"
      - "Академические достижения и трудности"
      - "Личностное развитие через образование"
    
  - id: 3
    name: "career_work"
    title: "Карьера и профессиональная жизнь"
    context_prompt: |
      Изучай профессиональный путь, учитывая образовательный фон и семейные ценности.
      Исследуй мотивацию к карьерным решениям, профессиональные цели и достижения.
      Обращай внимание на влияние предыдущего опыта на карьерный выбор и развитие.
    focus_areas:
      - "Карьерный путь и ключевые решения"
      - "Профессиональные цели и амбиции"
      - "Удовлетворение от работы и мотивация"
      - "Карьерные вызовы и их преодоление"
      - "Отношения на рабочем месте"
    
  - id: 4
    name: "relationships_social"
    title: "Отношения и социальные связи"
    context_prompt: |
      Исследуй сферу межличностных отношений, учитывая семейный опыт и профессиональное окружение.
      Изучай дружбы, романтические отношения, социальные навыки и предпочтения в общении.
      Ищи паттерны в отношениях, связанные с детством и семейными моделями.
    focus_areas:
      - "Паттерны дружеских отношений"
      - "Романтические отношения и партнерство"
      - "Социальные навыки и коммуникация"
      - "Стиль общения и предпочтения"
      - "Ценности в отношениях"
    
  - id: 5
    name: "values_beliefs"
    title: "Ценности и мировоззрение"
    context_prompt: |
      Изучай систему ценностей, убеждений и мировоззрения, сформированные через опыт семьи, образования и отношений.
      Исследуй этические принципы, жизненную философию и то, что человек считает важным.
      Обращай внимание на эволюцию взглядов и влияние жизненного опыта.
    focus_areas:
      - "Основные жизненные ценности"
      - "Жизненная философия и принципы"
      - "Этические убеждения и моральные ориентиры"
      - "Духовные или религиозные взгляды"
      - "Внутренний моральный компас"
    
  - id: 6
    name: "interests_creativity"
    title: "Увлечения и творчество"
    context_prompt: |
      Исследуй творческие интересы и хобби, учитывая личностные ценности и жизненный опыт.
      Изучай, как увлечения связаны с самовыражением и личностным развитием.
      Ищи связи между творчеством и другими аспектами жизни человека.
    focus_areas:
      - "Хобби и личные интересы"
      - "Творческое самовыражение"
      - "Художественные предпочтения и вкусы"
      - "Досуговые активности"
      - "Личные проекты и увлечения"
    
  - id: 7
    name: "health_lifestyle"
    title: "Здоровье и образ жизни"
    context_prompt: |
      Изучай подходы к здоровью, самочувствию и образу жизни, основанные на ценностях и жизненном опыте.
      Исследуй физическое и ментальное здоровье, привычки и заботу о себе.
      Обращай внимание на влияние стресса, работы и отношений на здоровье.
    focus_areas:
      - "Физическое здоровье и активность"
      - "Ментальное благополучие"
      - "Жизненные привычки и рутины"
      - "Управление стрессом"
      - "Практики самозаботы"
    
  - id: 8
    name: "challenges_growth"
    title: "Вызовы и личностный рост"
    context_prompt: |
      Исследуй жизненные трудности, препятствия и способы их преодоления, основываясь на всем предыдущем опыте.
      Изучай уроки, полученные из сложных ситуаций, и влияние на личностный рост.
      Ищи паттерны в том, как человек справляется с вызовами.
    focus_areas:
      - "Жизненные трудности и препятствия"
      - "Стратегии преодоления проблем"
      - "Факторы устойчивости и стрессоустойчивости"
      - "Личностный рост через трудности"
      - "Извлеченные уроки и выводы"
    
  - id: 9
    name: "achievements_pride"
    title: "Достижения и гордость"
    context_prompt: |
      Изучай достижения и моменты гордости, учитывая весь жизненный путь и преодоленные трудности.
      Исследуй, что человек считает своими успехами и источниками удовлетворения.
      Обращай внимание на связь достижений с ценностями и жизненными целями.
    focus_areas:
      - "Личные достижения и успехи"
      - "Источники гордости и удовлетворения"
      - "Определения успеха для человека"
      - "Ключевые вехи в жизни"
      - "Важность признания и оценки"
    
  - id: 10
    name: "future_vision"
    title: "Будущее и жизненные цели"
    context_prompt: |
      Завершай интервью, исследуя планы на будущее, мечты и цели, основанные на всем жизненном опыте.
      Изучай, как прошлый опыт влияет на видение будущего и планирование.
      Создай целостную картину человека, его стремлений и направления развития.
    focus_areas:
      - "Планы и цели на будущее"
      - "Жизненное видение и мечты"
      - "Стремления и амбиции"
      - "Планируемые изменения в жизни"
      - "Мысли о наследии и влиянии"

summary_structure:
  key_facts: []
  important_themes: []
  emotional_markers: []
  behavioral_patterns: []
  values_beliefs: []
  priorities: []
  sensitive_topics: []